### ISSUE TITLE
Basic user configuration

### ISSUE THREAD

**Issue by oz** [oz/tz#1]
The current "configuration story" simply loads a list of timezones from the environment variable `TZ_LIST`: this is just fine for me. The same could be said of the colors: they're just fine for my dark terminal... but probably not for everyone.

If I get enough complaints, maybe I'll consider making the colors a configuratble option, loaded from the user's config. directory. Then the `TZ_LIST` env var could either disappear or enhance a file configuration variable. 🤔

**Comment by GabMus** [comment]
As for colors you could give the option to just use the built-in terminal colors. That would work fine for most people I think.

**Comment by markstos** [comment]
I agree using the terminal colors should be sufficient. Also, using the environment variable seems like sufficient configuration support.

**Comment by wyne** [comment]
I have a draft of a feature to load configuration from a toml file instead. I think this could much more easily allow for color settings. https://github.com/wyne/tz/pull/1

**Comment by oz** [comment]
> I have a draft of a feature to load configuration from a toml file instead. I think this could much more easily allow for color settings. https://github.com/wyne/tz/pull/1

Thanks for the PR! I think that TOML could work well for config. 👍🏻


I'll take a look at the PR in a few days as I'll be offline and computer-less until next week. 🐢

**Comment by oz** [comment]
It's on the main branch now. Thanks @wyne ! 👍🏻
