### ISSUE TITLE
-q doesn't work

### ISSUE THREAD

**Issue by runeimp** [oz/tz#16]
1st off, great tool. Love it!

Now, I installed this tool via Homebrew on my MBP running macOS 10.14.6 Mojave. It works great except for the -q not working. I see that -q was only added to the repos main branch 15 hours ago so maybe it didn't make it into the release used on Homebrew. Just checked and Homebrew is currently using v0.4 and checking the v0.4 tag I see flag package using in main is not present. OK, no prob. Just a note for others who are confused then. Will the `-q` option be present in v0.5 then?

**Comment by oz** [comment]
Hey, thanks! I’ll cut a 0.5 release with the new flag some time this week. :)

I was going to suggest using `brew install tz --HEAD` but it looks like the existing formula would need to be updated too because it tries to fetch a default branch that does not exist here. 😬

**Comment by mitchblank** [comment]
Sorry about `install --HEAD` not working; I just opened a homebrew PR to fix that : https://github.com/Homebrew/homebrew-core/pull/73917
