### ISSUE TITLE
Suggestion: Auto build binaries for different OS on release

### ISSUE THREAD

**Issue by wneessen** [oz/tz#21]
I've recently discovered a nice Github workflow, that automagically creates binaries for (almost) all supported Go binary formats. Once a new Github release has been drafted, the action will build binaries (including a checksum file) for Linux, Windows, MacOS and *BSD and append it to the release page. This would help people without a go build environment to easily get hands on a tz-binary.

I've added the workflow to a project of mine, and it works like a charme. You can see an example here:
https://github.com/wneessen/apg.go/releases/tag/v0.2.9

The action can be found on Github Marketplace: https://github.com/marketplace/actions/go-release-binaries

Since Github workflows (to my knowledge) cannot be PR'ed, I link to the workflow files I am currently using, which have been proven to work w/o issues:
*BSD: https://github.com/wneessen/apg.go/blob/main/.github/workflows/release-bsd.yml
MacOS: https://github.com/wneessen/apg.go/blob/main/.github/workflows/release-darwin.yml
Linux: https://github.com/wneessen/apg.go/blob/main/.github/workflows/release-linux.yml
Windows: https://github.com/wneessen/apg.go/blob/main/.github/workflows/release-windows.yml

**Comment by oz** [comment]
Oh yes, I'll have a look at this. Thanks for the suggestion. 👍🏻
