### ISSUE TITLE
Cannot display more than 2 timezones

### ISSUE THREAD

**Issue by chris-aeviator** [oz/tz#24]
On arch, I am able to provide up to two timezones, any further timezone is ignored.

```
❯ TZ_LIST="Europe/Berlin;America/Santiago" tz

  What time is it?

  🕛 (CEST) Local 12:07PM, Sat 15
   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22

  🕕 (-04) America/Santiago 6:07AM, Sat 15
  18  19  20  21  22  23   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16


 
❯ TZ_LIST="Europe/Berlin;Asia/Bangkok;America/Santiago" tz

  What time is it?

  🕛 (CEST) Local 12:08PM, Sat 15
   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22

  🕛 (CEST) Europe/Berlin 12:08PM, Sat 15
   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
```

**Comment by oz** [comment]
Hey @chris-aeviator,

I think the version you're using is 0.5, right? If so, replace `;` with `,` and you should be fine (see [this version's README](https://github.com/oz/tz/tree/v0.5#configuration) if needed).

Sorry for the confusion: it does change with the upcoming 0.6 so the current README is ahead of the latest 0.5 release, but I haven't found the time to make a release. 😬
