### ISSUE TITLE
24 hour times

### ISSUE THREAD

**Issue by greg-minshall** [oz/tz#31]
thanks for the tool.  i would find it pleasant to have times displayed in 24-hour format, rather than "AM"/"PM".

**Comment by oz** [comment]
Hi Greg!

Thanks for filing an issue. I think that's a perfectly reasonable request. I'll add that to the list of "it should be configurable" things. 👍🏻

**Comment by greg-minshall** [comment]
thanks!  one thing, maybe "military" isn't the best description?  in Europe, for example, 24 hour time is standard in civilian life.  cheers.
