### ISSUE TITLE
Is 0.6.2 an actual release?

### ISSUE THREAD

**Issue by mitchblank** [oz/tz#34]
I noticed that a month ago a "v0.6.2" tag appeared in this repo: https://github.com/oz/tz/tags  (which currently matches `main` -- [e23d811](https://github.com/oz/tz/commit/e23d8118c45425e374305f7411486c2af1eb3dfb))

... but 0.6.1 is still the most recent "release" https://github.com/oz/tz/releases

Is this intentional?  Is that tag going to become a release later, or is last year's 0.6.1 still considered "current"?

I ask because right now homebrew is confused, because it's scanning the version-number-looking git tags in the repo:
```
$  brew livecheck --verbose tz
tz (guessed): 0.6.1 ==> 0.6.2
```
If 0.6.1 is really the correct "latest release" I can tweak the homebrew livecheck rules for that formula to only consider the github release page and ignore tags.  But I don't want to do that if 0.6.2 is merely an accidentally-forgotten release

**Comment by oz** [comment]
Hello there!
Sorry for forgetting the tag for so long. 😵

I've properly release 0.6.2.
