### ISSUE TITLE
Match names to timezones?

### ISSUE THREAD

**Issue by decentral1se** [oz/tz#37]
When working with several timezones on a daily basis, it can be confusing to remember which timezone corresponds to which person (or persons, in my case) you want to find a suitable time to meet with. It'd be great if we could include names which match timezones. Would be really handy if this would be configurable.

**Comment by oz** [comment]
Hi @decentral1se!

Thanks for taking the time to write about this.

If I understand correctly, you'd like to change the "label" of a time zone? You can already achieve that using a `,` to separate the tzdb-name of a time zone from its label.

For instance, while working with Mustapha in Dubaï, and Rodrigo in Canary, I could use something like:

```fish
env TZ_LIST='Asia/Dubai,Mustapha;Atlantic/Canary,Rodrigo' tz
```

Hope this helps!

**Comment by decentral1se** [comment]
Incredible @oz! Thank *you*!
