### ISSUE TITLE
Watch flag -w clashes with keyboard navigation and -when

### ISSUE THREAD

**Issue by jnd-au** [oz/tz#58]
The unreleased watch flag `-w` (057fc06) clashes with (a) keyboard navigation and (b) the `-when` option. That is, if the user:
- Specifies the `-w` watch flag,
- And either/both:
  - A specific time with `-when`; or
  - Uses left/right keyboard navigation to change the viewed time,
- Then a logical paradox occurs without warning:
  - The user’s requested time gets overwritten by the next minute’s tickMsg without warning.

**Comment by wyne** [comment]
What is the behavior you're expecting?

**Comment by jnd-au** [comment]
There are multiple possibilities, depending on personal preference, for example:
1. Emit an error message and abort, due to the conflicting user options
   - Pro: Makes sense for `-when` CLI option
   - Con: Doesn’t make sense when the user does left-right interactive keyboard navigation
1. Disable `-w` (watch) until `t` is pressed interactively
   - Pro: Full control to the user
   - Pro: Make senses when the user does left-right interactive keyboard navigation
   - Con: Silent acceptance of conflicting CLI options

I implemented Option 2 in PR #61.
