### ISSUE TITLE
Display name for selected TZ

### ISSUE THREAD

**Issue by cmaahs** [oz/tz#6]
enhancement

This may or may not be worthwhile for you.  I tend to think of the people I'm working with in terms of the city/country that they work in.  Since the standard TZ database is small by design, it doesn't really allow one to be specific.  For instance, America/Tampa Bay isn't a thing, and so you would choose America/New York or America/Detroit to get to the Eastern Time zone.  Off the top of my head, something like:

TZ_LIST=America/Detroit;Tampa Bay,America/Chicago;Minneapolis

Would allow one to display Tampa Bay and Minneapolis for those two time zones.  

Just a thought, I love the simplicity of the interface, and using TZ_LIST seems just fine, I didn't see, is there a way to get `tz` to list out the TZ names for a particular UTC offset?

**Comment by cmaahs** [comment]
All good, I know how it is with all the different thoughts after you get a project to a first release...

**Comment by oz** [comment]
Fixed in d1261d10, and in 0.2 release.

**Comment by cmaahs** [comment]
Thanks much!
