### ISSUE TITLE
Feature idea: Dates and times in the past and future

### ISSUE THREAD

**Issue by TechnologyClassroom** [oz/tz#8]
It would be cool to have an optional argument for a date in the future or past for scheduling events that are not today.

Usage could be something like this:

    tz -d $(date -d '+6 month' +%Y-%m-%d)

**Comment by oz** [comment]
I'll consider it, but if you don't toggle dates changes, then this is already a feature.

**Comment by oz** [comment]
Alright, this is on master.

**Comment by TechnologyClassroom** [comment]
That works.  Here is an example of usage with the date command which can output in UNIX time.

    tz -when $(date -d "+ 6 month + 3 hour" +"%s")
